# Generated by Django 2.0.6 on 2018-06-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Системные настройки', 'verbose_name_plural': 'Системные настройки'},
        ),
    ]
