# Generated by Django 2.0.6 on 2018-06-23 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_auto_20180623_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('amount_of_days', models.PositiveSmallIntegerField(verbose_name='Количество дней')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата старта майстоуна')),
            ],
            options={
                'verbose_name': 'Майлстоун',
                'verbose_name_plural': 'Майлстоуны',
                'ordering': ('index_number',),
            },
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('order',), 'verbose_name': 'Статус проекта', 'verbose_name_plural': 'Статусы проектов'},
        ),
        migrations.AddField(
            model_name='project',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сдачи проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата старта проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Проект менеджер'),
        ),
    ]
