# Generated by Django 2.0.6 on 2018-06-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, 'К выполнению'), (2, 'На проверку'), (3, 'Выполнено')], default=1, max_length=2, verbose_name='Статус'),
        ),
    ]
