# Generated by Django 2.0.6 on 2018-06-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20180623_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'К выполнению'), ('2', 'На проверку'), ('3', 'Выполнено')], default=1, max_length=2, verbose_name='Статус'),
        ),
    ]
