# Generated by Django 2.0.6 on 2018-06-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180623_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rate_per_hour',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='Ставка за час (USD)'),
            preserve_default=False,
        ),
    ]
