# Generated by Django 2.0.6 on 2018-06-27 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_user_rate_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ManyToManyField(related_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
